language: ruby
rvm:
  - 2.6.3

install:
  - bundle install
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

services:
  - postgresql

script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec
  - yarn
  - RAILS_ENV=development ./bin/webpack-dev-server
