language: ruby
rvm:
  - 2.6.3

install:
  - bundle install
  - nvm install
  - gem install bundler -v 1.16.4
  - cd package && npm install && cd -
  - cd test/dummy && yarn install && cd -

services:
  - postgresql

script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec
  - yarn test
  - RAILS_ENV=development ./bin/webpack-dev-server
