language: ruby
rvm:
  - 2.7.0

install:
  - bundle install
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

services:
  - postgresql

script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:seed
  - bundle exec rspec
