development:
  adapter: postgresql
  encoding: unicode
  database: training_dev
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: training_test
  pool: 5
  username:
  password:
