development:
  adapter: postgresql
  encoding: unicode
  database: training
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: training
  pool: 5
  username:
  password:
